### ISSUE TITLE
Bot looses connection to google API occasionaly

### ISSUE THREAD

**Issue by RosesHaveThorns** [cowminer27/FW_RedBot#3]
The issue resolves itself after the bot auto reconnects after the set period. Haven't found a link between the times the connection is lost yet. Unsure if it has happened recently, last confirmed time was _27-06-19 at 18:29:14_.

**Logs for the 3 known times it has happened:**

2019-06-15 17:23:22 >>> cowminer27: '$help' command called 9.459995273749033 minutes after last gsheets login
2019-06-15 17:23:22 >>> Command Succesfull
2019-06-15 17:23:33 >>> cowminer27: '$comradeshipevent' command called 9.633635453383128 minutes after last gsheets login
2019-06-15 17:23:33 >>> Command Data Collected
2019-06-15 17:24:35 >>> Pyrusapollo: '$comradeshipevent' command called 10.681651393572489 minutes after last gsheets login
2019-06-15 17:24:36 >>> Command Data Collected
2019-06-15 17:26:43 >>> Pyrusapollo: '$comradeshipevent' command called 12.808380206425985 minutes after last gsheets login
2019-06-15 17:26:43 >>> Command Data Collected
2019-06-15 17:27:18 >>> Pyrusapollo: '$comradeshiplevel' command called 13.392275222142537 minutes after last gsheets login
2019-06-15 17:29:36 >>> On_we_clash: '$comradeshiplevel' command called 15.695492096741994 minutes after last gsheets login
2019-06-15 17:29:45 >>> On_we_clash: '$comradeshiplevel' command called 15.833430051803589 minutes after last gsheets login
2019-06-15 17:30:20 >>> On_we_clash: '$help' command called 16.417445385456084 minutes after last gsheets login
2019-06-15 17:30:20 >>> Command Succesfull
2019-06-15 17:30:29 >>> On_we_clash: '$comradeshiplevel' command called 16.57069027821223 minutes after last gsheets login
2019-06-15 17:30:39 >>> Pyrusapollo: '$comradeshiplevel' command called 16.737277734279633 minutes after last gsheets login
2019-06-15 17:31:02 >>> On_we_clash: '$comradeshiplevel' command called 17.132239095369975 minutes after last gsheets login
2019-06-15 17:47:03 >>> Time since last gsheets login is 33.14121840397517 minutes
2019-06-15 17:47:03 >>> Avoiding timeout; Logging back in to gsheets
2019-06-15 17:57:41 >>> On_we_clash: '$comradeshipevent' command called 10.574215376377106 minutes after last gsheets login
2019-06-15 17:57:41 >>> Command Data Collected
2019-06-15 17:57:41 >>> Found username, updating spreadsheet
2019-06-15 17:57:42 >>> Command Succesfull`

2019-06-17 17:36:12 >>> On_we_clash: '$comradeshiplevel' command called 0.4494186520576477 minutes after last gsheets login
2019-06-17 17:36:15 >>> Command Succesfull
2019-06-17 17:36:47 >>> On_we_clash: '$comradeshiplevel' command called 1.032252021630605 minutes after last gsheets login
2019-06-17 17:37:45 >>> On_we_clash: '$comradeshiplevel' command called 1.9964364210764567 minutes after last gsheets login
2019-06-17 17:42:13 >>> On_we_clash: '$comradeshipevent' command called 6.463472485542297 minutes after last gsheets login
2019-06-17 17:42:13 >>> Command Data Collected`

2019-06-27 17:29:43 >>> Reals26: '$honstatus' command called 12.948614291350047 minutes after last gsheets login
2019-06-27 17:29:45 >>> Found Username
2019-06-27 17:29:46 >>> Collected Cell Values
2019-06-27 17:29:46 >>> Command Succesfull
2019-06-27 18:09:59 >>> Time since last gsheets login is 53.21212087074915 minutes
2019-06-27 18:09:59 >>> Avoiding timeout; Logging back in to gsheets
2019-06-27 18:29:14 >>> Tetsu44: '$honupdate' command called 19.184830904006958 minutes after last gsheets login

**Comment by RosesHaveThorns** [comment]
possibly happened again:
but think this was different, possibly caused by bad timing with the dice error (no longer an issue)

Ignoring exception in command dice:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Redbot/CogsRewrite/cogs/Games.py", line 34, in dice
    out = "The " + input + " sided die Landed On a **" + str(random.randint(1, max)) + "**"
  File "/usr/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,-99, -100)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 859, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 725, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: empty range for randrange() (1,-99, -100)
Ignoring exception in command dice:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Redbot/CogsRewrite/cogs/Games.py", line 36, in dice
    await msgOut.edit(content=out)
  File "/usr/local/lib/python3.6/dist-packages/discord/message.py", line 680, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In content: Must be 2000 or fewer in length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 859, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 725, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In content: Must be 2000 or fewer in length.
Ignoring exception in command honstatus:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Redbot/CogsRewrite/cogs/HonRed.py", line 33, in honstatus
    sheetUsernames = self.honSheetMain.col_values(1)
  File "/usr/local/lib/python3.6/dist-packages/gspread/models.py", line 693, in col_values
    'majorDimension': 'COLUMNS'
  File "/usr/local/lib/python3.6/dist-packages/gspread/models.py", line 148, in values_get
    r = self.client.request('get', url, params=params)
  File "/usr/local/lib/python3.6/dist-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 859, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 725, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}

Ignoring exception in command honstatus:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Redbot/CogsRewrite/cogs/HonRed.py", line 33, in honstatus
    sheetUsernames = self.honSheetMain.col_values(1)
  File "/usr/local/lib/python3.6/dist-packages/gspread/models.py", line 693, in col_values
    'majorDimension': 'COLUMNS'
  File "/usr/local/lib/python3.6/dist-packages/gspread/models.py", line 148, in values_get
    r = self.client.request('get', url, params=params)
  File "/usr/local/lib/python3.6/dist-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 859, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 725, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}

**Comment by RosesHaveThorns** [comment]
Seems to be resolved, closing this
